spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  logging:
    level:
      root: DEBUG
  datasource:
    url: jdbc:mysql://localhost:3306/ItBridge?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123!
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 기존 AntPathMatcher를 사용하도록 설정
  resources:
    add-mappings: ant_path_matcher
    web:
      mime-types:
        css: text/css
        js: application/javascript
        springdoc:
          api-docs:
            path: /v3/api-docs
          swagger-ui:
            path: /swagger-ui.html
            resources:
              static-locations: classpath:/static/, file:src/main/resources/static/
token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@
  access-token:
    plus-hour: 24
  refresh-token:
    plus-hour: 24


