## MySQL 공식 이미지 사용
#FROM mysql:8.4
#
## 환경 변수 설정 (기본 설정)
#ENV MYSQL_ROOT_PASSWORD=root123!
#ENV MYSQL_DATABASE=ItBridge
#
## 초기 SQL 스크립트 복사 (선택 사항)
#COPY schema.sql /docker-entrypoint-initdb.d/
#
## 기본 포트
#EXPOSE 3306